### ISSUE TITLE
Vorschlag, Unterstützung für Funktionen wie XTLS 和 CDN VLESS hinzuzufügen

### ISSUE THREAD

**Issue by Wallphd** [ProxyPanel/VNet-V2ray#3]
Vorschlag, Unterstützung für Funktionen wie XTLS 和 CDN VLESS hinzuzufügen
Ich hoffe, dass wir später eine bessere Erfahrung machen werden！

**Comment by ZBrettonYe** [comment]
Speak English or Chinese. Don't pretend u r from German!
